image: node

stages:
  - build
  - lint
  - test

build:
  stage: build
  script:
    - npm install next
    - npm run build

lint:
  stage: lint
  script:
    - npm install eslint
    - npm run lint

test:
  stage: test
  script:
    - npm install jest
    - npm test
