image: node

stages:
  - build
  - lint

build:
  stage: build
  script:
    - npm install
    - npm run build

lint:
  stage: lint
  script:
    - npm install eslint
    - npm run lint

test:
  stage: test
  script:
    - npm test
